# Global settings applied to the whole site
[build]
  publish = "dist"  # Adjust this to your build output directory
  command = "npm run build"  # Adjust this to your build command

# Redirect and rewrite rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
